#!/usr/bin/env bash

docker run \
  --rm \
  --name vibe-sandbox \
  --security-opt no-new-privileges=true \
  --cpus 2.0 \
  --memory 1G \
  --pull "always" \
  -it \
  -v "${PWD}:/workspace" \
  -v "${HOME}/.vibe-sandbox:/home/vibe-user/.vibe" \
  -v /etc/localtime:/etc/localtime:ro \
  -v /etc/timezone:/etc/timezone:ro \
  nachtsieb/vibe-sandbox:latest \
  "$@"
